[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["python311", "gcc"]

[deploy]
healthcheckPath = "/api/health/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
