# Generated by Django 5.2.11 on 2026-02-25 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='hod',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'HOD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_subject', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.CharField(choices=[('Form 1', 'Form 1'), ('Form 2', 'Form 2'), ('Form 3', 'Form 3'), ('Form 4', 'Form 4'), ('Form 5', 'Form 5'), ('Lower Sixth', 'Lower Sixth'), ('Upper Sixth', 'Upper Sixth')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'TEACHER'}, related_name='assigned_subjects', to=settings.AUTH_USER_MODEL),
        ),
    ]
