# Generated by Django 5.2.11 on 2026-02-25 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_subject_hod_alter_subject_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'HOD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_department', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='type',
            field=models.CharField(choices=[('CORE', 'Core Department (Science, Arts, etc.)'), ('SUBJECT', 'Subject Department (Biology, Chemistry, etc.)')], default='CORE', max_length=10),
        ),
    ]
