# Generated by Django 5.2.11 on 2026-02-26 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_department_hod_department_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_subjects', to='academic.department')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='base_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='academic.basesubject'),
        ),
    ]
