# Generated by Django 5.2.11 on 2026-02-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_basesubject_subject_base_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('VOCATIONAL', 'Vocational')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='stream',
            field=models.CharField(choices=[('NONE', 'None'), ('ARTS', 'Arts'), ('SCIENCE', 'Science'), ('COMMERCIAL', 'Commercial'), ('TECHNICAL', 'Technical')], default='NONE', max_length=20),
        ),
    ]
