# Generated by Django 5.2.11 on 2026-02-26 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_subject_category_subject_stream'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='category',
            new_name='domain',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='stream',
            new_name='sub_domain',
        ),
    ]
