# Generated by Django 5.2.11 on 2026-02-26 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_rename_category_subject_domain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='subject',
            name='hod',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'HOD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_subjects_hod', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basesubject',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_subjects', to='academic.domain'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='academic.domain'),
        ),
        migrations.CreateModel(
            name='SubDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_domains', to='academic.domain')),
            ],
            options={
                'unique_together': {('domain', 'name')},
            },
        ),
        migrations.AddField(
            model_name='basesubject',
            name='sub_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_subjects', to='academic.subdomain'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='academic.subdomain'),
        ),
    ]
