# Generated by Django 5.2.11 on 2026-02-27 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_domain_alter_subject_hod_basesubject_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_levels', to='academic.domain')),
                ('sub_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_levels', to='academic.subdomain')),
            ],
            options={
                'ordering': ['domain', 'sub_domain', 'name'],
                'unique_together': {('name', 'domain', 'sub_domain')},
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='academic_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academic.academiclevel'),
        ),
    ]
