# Generated by Django 5.2.11 on 2026-02-26 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_domain_alter_subject_hod_basesubject_domain_and_more'),
        ('content', '0002_assignment_curriculumtopic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='academic.domain'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='sub_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='academic.subdomain'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_class',
            field=models.CharField(blank=True, help_text="e.g. 'Form 4', 'Upper Sixth'", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='level',
            field=models.CharField(choices=[('SCHOOL', 'School-wide'), ('DOMAIN', 'Domain-level'), ('SUBDOMAIN', 'Sub-domain level'), ('CLASS', 'Class / Level'), ('SUBJECT', 'Subject-level')], max_length=20),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
