# Generated by Django 5.2.11 on 2026-02-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='raw_pdf',
        ),
        migrations.AddField(
            model_name='quiz',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Last date/time for students to attempt', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='raw_file',
            field=models.FileField(blank=True, help_text='PDF or DOCX source file', null=True, upload_to='quizzes/raw/'),
        ),
    ]
