# Generated by Django 5.2.11 on 2026-02-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_add_deadline_raw_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='can_retake',
            field=models.BooleanField(default=False),
        ),
    ]
