# Generated by Django 5.2.11 on 2026-03-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_attemptanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
