# Generated by Django 5.2.11 on 2026-02-25 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_subject_hod_alter_subject_level_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hodprofile',
            name='department',
        ),
        migrations.AddField(
            model_name='hodprofile',
            name='subject',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_hod', to='academic.subject'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.CharField(max_length=20),
        ),
    ]
