# Generated by Django 5.2.11 on 2026-02-25 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_department_hod_department_type'),
        ('accounts', '0002_remove_hodprofile_department_hodprofile_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hodprofile',
            name='department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_hod_profile', to='academic.department'),
        ),
        migrations.AlterField(
            model_name='hodprofile',
            name='subject',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_hod_profile', to='academic.subject'),
        ),
    ]
