# Generated by Django 5.2.11 on 2026-02-26 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_domain_alter_subject_hod_basesubject_domain_and_more'),
        ('accounts', '0003_hodprofile_department_alter_hodprofile_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academic.domain'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='sub_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academic.subdomain'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academic.department'),
        ),
    ]
