# Generated by Django 5.2.11 on 2026-02-27 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_alter_subject_level_academiclevel_and_more'),
        ('accounts', '0004_studentprofile_domain_studentprofile_sub_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='academic_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academic.academiclevel'),
        ),
    ]
