# Generated by Django 5.2.11 on 2026-02-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentprofile_academic_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
